name: email trigger

on:
  schedule:
    - cron: '07 00 * * *'
      timezone: "Asia/Kolkata"

  workflow_dispatch:

permissions: write-all

jobs:
  Email_Trigger:
    name: Email_Trigger
    runs-on: ubuntu-22.04

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Python check
        run: |
          which python
          python --version
          python -c "import requests; print('requests:', requests.__version__)"
          python -c "from bs4 import BeautifulSoup; print('BeautifulSoup: OK')"

      - name: Trigger Emails
        run: |
          python process_emails2.py
